import type { Metadata } from 'next';
import { montserrat } from '@/components/fonts';
import { Header } from './_components/header';
import { Footer } from './_components/footer';
import '../../globals.css';

export const metadata: Metadata = {
  title: 'InsightGathers',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-colorsecondary ${montserrat.className} overflow-x-hidden antialiased`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
